name: CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: windows-latest
    name: Android Build
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x
          
      - name: Install MAUI Workload
        run: dotnet workload install maui-windows maui-android --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore MediaWikiClient/MediaWikiClient.csproj

      - name: Build MAUI Android
        run: dotnet publish MediaWikiClient/MediaWikiClient.csproj -c Release -f net7.0-android -r android-arm64

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: mediawikiclient-android-ci-build
          path: MediaWikiClient/bin/Release/net7.0-android/

# MAUI Windows Build
  build-windows:
    runs-on: windows-latest
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui-windows maui-android --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore MediaWikiClient/MediaWikiClient.csproj

      - name: Build MAUI Windows
        run: dotnet publish MediaWikiClient/MediaWikiClient.csproj -c Release -f net7.0-windows10.0.19041.0

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: mediawikiclient-windows-ci-build
          path: MediaWikiClient/bin/Release/net7.0-windows10.0.19041.0/